### PR TITLE
Pass cause exception through to Exception's __construct as $previous

### LINKED ISSUE #44: shouldBeConnected() throws away exception information (stack trace, etc.)
[This exception handler](https://github.com/mariano/disque-php/blob/39bc697d6307adb742a7d85bda9aa8aee76eca48/src/Connection/Manager.php#L402) doesn't pass the caught exception to the new exception's constructor argument (i.e. the third argument in `Exception`'s `__construct($message = "", $code = 0, Exception $previous = null)`)

This means the stack trace and original exception information are lost. Generally, only getting `$e->getMessage()` makes debugging hard, even compared to `(string)$e` if you _must_ serialize it.

I'd love to be able to fix this in an injected `ConnectionManager`, but the default `Manager` implementation (~500 lines) is closed for extension: reimplementing `shouldBeConnected()` requires `switchNodeIfNeeded()`, which requires `switchToNode()`, which requires `copyNodeStats()`, `resetNodeCounters()`, etc. There is a protected API, but it just doesn't provide any extension points suitable for overriding `shouldBeConnected()`.

### PR DESCRIPTION
**Pull request by dominics**
Fixes #44 

No reason to go with 0 for the code argument (but that's the default value as is, so not a change.)

### CODE REVIEW

File: src/Connection/Manager.php [hunk 1]
```diff
@@ -321,6 +324,8 @@ private function switchNodeIfNeeded()
             $this->nodeId
         );
 
+        $previous = null;
```
Comment (Revisor) [inline src/Connection/Manager.php:327]: I know it's already merged, but `$previous` is not a very good variable name, for anything.

Comment (dominics) [reply src/Connection/Manager.php:327]: Rationale: that's the name of the parameter in `Exception::__construct()`: https://github.com/php/php-src/blob/c6982995504b6e21e8a5ade29cfb16a55196dc43/Zend/zend_exceptions.c#L772
